data <- c(3,5,6,2,7,3,9,4)
print(data)
mean_value <- mean(data)
print(paste("Mean = ",mean_value))
med_value <- median(data)
print(paste("Median = ", med_value))
mode_function <- function(x){
		uniq_values <-unique(x)
		uniq_values[which.max(tabulate(match(x,uniq_values)))]
}
mode_value <- mode_function(data)
print(paste("Mode= ",mode_value))
max_value <- max(data)
print(paste("maximum =",max_value))
min_value <- min(data)
print(paste("minimum =",min_value))
var_value <- var(data)
print(paste("Varience =",var_value))
sd_value <- sd(data)
print(paste("Std =",sd_value))
a <- barplot(data)
print(paste("Bar plot",a))
b <- summary(data)
print(paste("summary",b))
c <- pie(data)
print(paste("Pie=",c))